modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Unlicense"

[[mods]]
modId = "snoisium"
version = "${version}"
displayName = "SNoisium"
authors = "Sixik"
description = '''

'''
#logoFile = ""

[[dependencies.snoisium]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.snoisium]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "snoisium.mixins.json"
